/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.chess.swingComponents.contentPanel.gamePanel;

/**
 *
 * @author guilh
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginScreen1 = new com.mycompany.chess.swingComponents.contentPanel.gamePanel.loginScreen.LoginScreen();
        gameScreen1 = new com.mycompany.chess.swingComponents.contentPanel.gamePanel.gameScreen.GameScreen();

        setMinimumSize(new java.awt.Dimension(1009, 688));
        setPreferredSize(new java.awt.Dimension(1009, 688));
        setLayout(new java.awt.CardLayout());
        add(loginScreen1, "card2");
        add(gameScreen1, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.chess.swingComponents.contentPanel.gamePanel.gameScreen.GameScreen gameScreen1;
    private com.mycompany.chess.swingComponents.contentPanel.gamePanel.loginScreen.LoginScreen loginScreen1;
    // End of variables declaration//GEN-END:variables
}
