/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.chess.swingComponents.contentPanel.gamePanel.board;

import com.mycompany.chess.swingComponents.contentPanel.gamePanel.board.pieces.Piece;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author guilh
 */
public class Square extends javax.swing.JPanel {
    private Position position;
    private Piece piece;
    /**
     * Creates new form Square
     */
    public Square(int x, int y, boolean brown, int height) {
        initComponents();
        this.position = new Position(x, y);
        if(brown){
            setBackground(new Color(177,110,65));
        }else{
            setBackground(new Color(251,209,151));
        }
        setPreferredSize(new Dimension(height, height));
    }
    
    public void setPiece(Piece piece){
        this.piece = piece;
        removeAll();
        if(piece != null){
            JLabel pieceLabel = new JLabel(piece.getIcon());
            add(pieceLabel);
        }
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
