//Victor Wingert de Almeida         - 202335036
//Guilherme Roldão dos Reis Pimenta - 202365085A
//Bruno Nascimento Rodrigues        - 202065114A
//Pablo Novaes Costa                - 202335031

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.chess.swingComponents.contentPanel.TournamentPanel;

import com.mycompany.chess.swingComponents.contentPanel.replaysPanel.ReplayGameScreen;
import entitites.Player;
import entitites.TournamentMatch;
import java.awt.CardLayout;
import java.util.List;
import entitites.Tournament;

/**
 *
 * @author guilh
 */
public class TournamentPanel extends javax.swing.JPanel {

    /**
     * Creates new form TournamentPanel
     */
    private CardLayout cardLayout;
    private TournamentPanelTournamentsTable tournamentPanelTournamentTable;
    private MatchesListPanel matchesListPanel;
    private TournamentPanelTournamentsTable tournamentPanelTournamentsTable;
    private TournamentGamePanel tournamentGamePanel;

    public TournamentPanel() {
        initComponents();
        cardLayout = (CardLayout) this.getLayout();
        tournamentPanelTournamentsTable = new TournamentPanelTournamentsTable();
        add(tournamentPanelTournamentsTable, "tournamentPanelTournamentsTable");
        tournamentPanelTournamentsTable.setTournamentPanel(this);
        cardLayout.show(this, "tournamentPanelTournamentsTable");;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    public void updateTournamentTable() {
        tournamentPanelTournamentsTable.refreshTable();
    }

    public void goToMatchesListPanel(Tournament tournament) {
        matchesListPanel = new MatchesListPanel(tournament);
        add(matchesListPanel, "matchesListPanel");
        matchesListPanel.setTournamentPanel(this);
        cardLayout.show(this, "matchesListPanel");
    }

    public void goToTournamentsTable() {
        tournamentPanelTournamentsTable.refreshTable();
        cardLayout.show(this, "tournamentPanelTournamentsTable");
    }

    public void goToTournamentGamePanel(Player player1ToCheck, Player player2ToCheck, Tournament tournament, TournamentMatch tournamentMatch) {
        tournamentGamePanel = new TournamentGamePanel(player1ToCheck, player2ToCheck, tournament, tournamentMatch);
        add(tournamentGamePanel, "tournamentGamePanel");
        cardLayout.show(this, "tournamentGamePanel");
    }

    public void resetPanel() {
        for (java.awt.Component component : getComponents()) {
            if (component != tournamentPanelTournamentsTable) {
                remove(component);
            }
        }
        revalidate();
        repaint();

        cardLayout.show(this, "tournamentPanelTournamentsTable");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
