//Victor Wingert de Almeida         - 202335036
//Guilherme Roldão dos Reis Pimenta - 202365085A
//Bruno Nascimento Rodrigues        - 202065114A
//Pablo Novaes Costa                - 202335031

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.chess.swingComponents.contentPanel.replaysPanel;

/**
 *
 * @author guilh
 */
public class ReplayGameScreen extends javax.swing.JPanel {
    private int numberOfStates;
    private int stateIndex = 0;
    private ReplayBoard replayBoard;
    private ReplaysPanel replaysPanel;
    /**
     * Creates new form ReplayGameScreen
     */
    public ReplayGameScreen(Replay replay) {
        initComponents();
        player1Label.setText("Branco: " + replay.getPlayer1Name());
        player2Label.setText("Preto: " + replay.getPlayer2Name());
        numberOfStates = replay.getStatesList().size();
        replayBoard = new ReplayBoard(replay.getStatesList());
        add(replayBoard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Label = new javax.swing.JLabel();
        prevStateButton = new com.mycompany.chess.swingComponents.sidebar.SidebarButton();
        turnCount = new javax.swing.JLabel();
        nextStateButton = new com.mycompany.chess.swingComponents.sidebar.SidebarButton();
        exitButton = new com.mycompany.chess.swingComponents.sidebar.SidebarButton();
        player2Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(1009, 688));

        player1Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        player1Label.setForeground(new java.awt.Color(255, 255, 255));
        player1Label.setText("jLabel1");
        add(player1Label);

        prevStateButton.setBackground(new java.awt.Color(255, 255, 255));
        prevStateButton.setForeground(new java.awt.Color(51, 51, 51));
        prevStateButton.setText("Voltar");
        prevStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevStateButtonActionPerformed(evt);
            }
        });
        add(prevStateButton);

        turnCount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        turnCount.setForeground(new java.awt.Color(255, 255, 255));
        turnCount.setText("Turno: 1");
        add(turnCount);

        nextStateButton.setBackground(new java.awt.Color(255, 255, 255));
        nextStateButton.setForeground(new java.awt.Color(51, 51, 51));
        nextStateButton.setText("Avançar");
        nextStateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStateButtonActionPerformed(evt);
            }
        });
        add(nextStateButton);

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setForeground(new java.awt.Color(51, 51, 51));
        exitButton.setText("Sair");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        add(exitButton);

        player2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        player2Label.setForeground(new java.awt.Color(255, 255, 255));
        player2Label.setText("jLabel1");
        add(player2Label);
    }// </editor-fold>//GEN-END:initComponents

    private void nextStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStateButtonActionPerformed
        // TODO add your handling code here:
        if(stateIndex < numberOfStates -1){
            stateIndex++;
            replayBoard.updateBoard(stateIndex);
            turnCount.setText("Turno: " + String.valueOf(stateIndex + 1));
        }
    }//GEN-LAST:event_nextStateButtonActionPerformed

    private void prevStateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevStateButtonActionPerformed
        // TODO add your handling code here:
        if(stateIndex > 0){
            stateIndex--;
            replayBoard.updateBoard(stateIndex);
            turnCount.setText("Turno: " + String.valueOf(stateIndex + 1));
        }
    }//GEN-LAST:event_prevStateButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        replaysPanel.goToReplaysTable();
    }//GEN-LAST:event_exitButtonActionPerformed
    
    public void setReplaysPanel(ReplaysPanel replaysPanel){
        this.replaysPanel = replaysPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.chess.swingComponents.sidebar.SidebarButton exitButton;
    private com.mycompany.chess.swingComponents.sidebar.SidebarButton nextStateButton;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2Label;
    private com.mycompany.chess.swingComponents.sidebar.SidebarButton prevStateButton;
    private javax.swing.JLabel turnCount;
    // End of variables declaration//GEN-END:variables
}
