/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.chess.swingComponents.contentPanel.replaysPanel;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.MouseInputAdapter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author guilh
 */
public class ReplaysPanel extends javax.swing.JPanel {
    private CardLayout cardLayout;
    private ReplayGameScreen replayGameScreen;
    /**
     * Creates new form ReplaysPanel
     */
    public ReplaysPanel() {
        initComponents();
        cardLayout = (CardLayout) this.getLayout();
        replaysTable1.setReplaysPanel(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replaysTable1 = new com.mycompany.chess.swingComponents.contentPanel.replaysPanel.ReplaysTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());
        add(replaysTable1, "card2");
    }// </editor-fold>//GEN-END:initComponents
    public void refreshReplaysTable(){
        replaysTable1.refreshReplayTable();
    }
    
    public void goToReplayGameScreen(Replay replay){
        replayGameScreen = new ReplayGameScreen(replay);
        add(replayGameScreen, "replayGameScreen");
        replayGameScreen.setReplaysPanel(this);
        cardLayout.show(this, "replayGameScreen");
    }
    
    public void goToReplaysTable(){
        remove(replayGameScreen);
        cardLayout.show(this, "card2");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.chess.swingComponents.contentPanel.replaysPanel.ReplaysTable replaysTable1;
    // End of variables declaration//GEN-END:variables
}
